language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: generic

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export PATH=/Users/travis/Library/Python/2.7/bin:$PATH;
        pip install --user -r scripts/requirements.txt;
      else
        pip install -r scripts/requirements.txt;
      fi

script:
- cd scripts/test && pytest -v
