language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: generic

install:
  - pip install --user -r scripts/requirements.txt

script:
  - cd scripts/test && pytest -v
